# Generated by Django 4.2.3 on 2023-08-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
