# Generated by Django 4.2.3 on 2023-08-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='post',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
